CWD := $(shell pwd)
OS := $(shell uname -s)
ARCH := $(shell uname -m)
LIBS = lib/ameba lib/clang

default: all

lint: shards
	bin/ameba
	crystal tool format -e src/lib-simde.cr --check
.PHONY: lint

clean:
	rm -f bin/demo
	rm -f bin/*.dwarf
	rm -rf lib
.PHONY: clean

all: vendor-libs shards
.PHONY: all

shards: shard.lock
.PHONY: shards

shard.lock: shard.yml
	shards install --ignore-crystal-version

############################
# Vendored Native Libraries
############################

lib/clang/bin/c2cr: shards lib/clang
	@cd lib/clang && shards build --release --ignore-crystal-version

vendor-libs: vendor-simde
.PHONY: vendor-libs

LIB_SIMDE_ARTIFACTS := vendor/simde-amalgamated
LIB_SIMDE_SUPPORTED_ARCH_X86 := x86_64 i386
LIB_SIMDE_SUPPORTED_ARCH_ARM := aarch64 arm
LIB_SIMDE_X86 := $(findstring ${ARCH},${LIB_SIMDE_SUPPORTED_ARCH_X86})
LIB_SIMDE_ARM := $(findstring ${ARCH},${LIB_SIMDE_SUPPORTED_ARCH_ARM})
LIB_SIMDE_ARCH := $(findstring ${ARCH},${LIB_SIMDE_SUPPORTED_ARCH_X86} ${LIB_SIMDE_SUPPORTED_ARCH_ARM})
ifeq (${LIB_SIMDE_X86},${ARCH})
	LIB_SIMDE_DIR := $(shell pwd)/vendor/simde-amalgamated/x86
endif
ifeq (${LIB_SIMDE_ARM},${ARCH})
	LIB_SIMDE_DIR := $(shell pwd)/vendor/simde-amalgamated/arm
endif

vendor/simde-amalgamated: vendor/simde.cr
	crystal vendor/simde.cr

vendor-simde: ${LIB_SIMDE_ARTIFACTS}
ifneq (${LIB_SIMDE_ARCH},${ARCH})
	$(error Unsupported platform (${ARCH}) for native dependency SIMDe!)
endif
ifeq (${LIB_SIMDE_X86},${ARCH})
	$(info Using x86 SIMDe sources from ${LIB_SIMDE_DIR})
endif
ifeq (${LIB_SIMDE_ARM},${ARCH})
	$(info Using arm SIMDe sources from ${LIB_SIMDE_DIR})
endif
	LIB_SIMDE_ARTIFACTS += $(shell file $(LIB_SIMDE_DIR) -n '*.h')
	CFLAGS += --link-flags ${LIB_SIMDE_ARTIFACTS}
.PHONY: vendor-simde

src/lib-simde.cr: lib/clang/bin/c2cr ${LIB_SIMDE_ARTIFACTS}
	@echo "# AUTOGENERATED: DO NOT EDIT!" > src/lib-simde.cr
	@echo "@[Link(ldflags: \"-L#{__DIR__}/../bin/libs -lsimde_native\")]" >> src/lib-simde.cr
	lib/clang/bin/c2cr -Ivendor simde.h --remove-enum-prefix=simde >> src/lib-simde.cr
	$(info Remember to follow instructions in src/lib-simde.cr)

###########
# Examples
###########

example-demo: vendor-libs
	crystal build examples/demo.cr -o examples/demo ${CFLAGS}
	bin/demo
.PHONY: example-demo
